// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/channel/v1/channel.proto (package spawner.channel.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { Actor } from "../../actor/v1/actor_pb.js";

/**
 * @generated from enum spawner.channel.v1.ChannelControllerType
 */
export const ChannelControllerType = /*@__PURE__*/ proto3.makeEnum(
  "spawner.channel.v1.ChannelControllerType",
  [
    {no: 0, name: "CHANNEL_CONTROLLER_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "CHANNEL_CONTROLLER_TYPE_CREATE", localName: "CREATE"},
    {no: 2, name: "CHANNEL_CONTROLLER_TYPE_LEAVE", localName: "LEAVE"},
  ],
);

/**
 * @generated from message spawner.channel.v1.ChannelHost
 */
export const ChannelHost = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.channel.v1.ChannelHost",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message spawner.channel.v1.ChannelMember
 */
export const ChannelMember = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.channel.v1.ChannelMember",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message spawner.channel.v1.ChannelController
 */
export const ChannelController = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.channel.v1.ChannelController",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(ChannelControllerType) },
    { no: 2, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "host", kind: "message", T: ChannelHost },
    { no: 4, name: "members", kind: "message", T: ChannelMember, repeated: true },
    { no: 5, name: "actor", kind: "message", T: Actor },
  ],
);

