// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/error/v1/error.proto (package spawner.error.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum spawner.error.v1.StatusCode
 */
export declare enum StatusCode {
  /**
   * @generated from enum value: STATUS_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_CODE_OK = 1;
   */
  OK = 1,

  /**
   * @generated from enum value: STATUS_CODE_CANCELLED = 2;
   */
  CANCELLED = 2,

  /**
   * @generated from enum value: STATUS_CODE_UNKNOWN = 3;
   */
  UNKNOWN = 3,

  /**
   * @generated from enum value: STATUS_CODE_INVALID_ARGUMENT = 4;
   */
  INVALID_ARGUMENT = 4,

  /**
   * @generated from enum value: STATUS_CODE_DEADLINE_EXCEEDED = 5;
   */
  DEADLINE_EXCEEDED = 5,

  /**
   * @generated from enum value: STATUS_CODE_NOT_FOUND = 6;
   */
  NOT_FOUND = 6,

  /**
   * @generated from enum value: STATUS_CODE_ALREADY_EXISTS = 7;
   */
  ALREADY_EXISTS = 7,

  /**
   * @generated from enum value: STATUS_CODE_PERMISSION_DENIED = 8;
   */
  PERMISSION_DENIED = 8,

  /**
   * @generated from enum value: STATUS_CODE_RESOURCE_EXHAUSTED = 9;
   */
  RESOURCE_EXHAUSTED = 9,

  /**
   * @generated from enum value: STATUS_CODE_FAILED_PRECONDITION = 10;
   */
  FAILED_PRECONDITION = 10,

  /**
   * @generated from enum value: STATUS_CODE_ABORTED = 11;
   */
  ABORTED = 11,

  /**
   * @generated from enum value: STATUS_CODE_OUT_OF_RANGE = 12;
   */
  OUT_OF_RANGE = 12,

  /**
   * @generated from enum value: STATUS_CODE_UNIMPLEMENTED = 13;
   */
  UNIMPLEMENTED = 13,

  /**
   * @generated from enum value: STATUS_CODE_INTERNAL = 14;
   */
  INTERNAL = 14,

  /**
   * @generated from enum value: STATUS_CODE_UNAVAILABLE = 15;
   */
  UNAVAILABLE = 15,

  /**
   * @generated from enum value: STATUS_CODE_DATA_LOSS = 16;
   */
  DATA_LOSS = 16,

  /**
   * @generated from enum value: STATUS_CODE_UNAUTHENTICATED = 17;
   */
  UNAUTHENTICATED = 17,
}

/**
 * Indicates and provides information on errors.
 *
 * @generated from message spawner.error.v1.ErrorEvent
 */
export declare class ErrorEvent extends Message<ErrorEvent> {
  /**
   * Output only.
   *
   * @generated from field: spawner.error.v1.StatusCode code = 1;
   */
  code: StatusCode;

  /**
   * Output only. A developer-facing message, in English.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  constructor(data?: PartialMessage<ErrorEvent>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "spawner.error.v1.ErrorEvent";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ErrorEvent;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ErrorEvent;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ErrorEvent;

  static equals(a: ErrorEvent | PlainMessage<ErrorEvent> | undefined, b: ErrorEvent | PlainMessage<ErrorEvent> | undefined): boolean;
}

