// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file spawner/quest/v1/quest.proto (package spawner.quest.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/quest/v1/quest.proto.
 */
export const file_spawner_quest_v1_quest: GenFile = /*@__PURE__*/
  fileDesc("ChxzcGF3bmVyL3F1ZXN0L3YxL3F1ZXN0LnByb3RvEhBzcGF3bmVyLnF1ZXN0LnYxIlsKClF1ZXN0RXZlbnQSDAoEbmFtZRgBIAEoCRIRCgljdXN0b21faWQYAiABKAkSFwoPaXNzdWVyX2FnZW50X2lkGAMgASgJEhMKC2ZsYXZvcl90ZXh0GAQgASgJQoQBChRjb20uc3Bhd25lci5xdWVzdC52MUIKUXVlc3RQcm90b1ABogIDU1FYqgIQU3Bhd25lci5RdWVzdC5WMcoCEFNwYXduZXJcUXVlc3RcVjHiAhxTcGF3bmVyXFF1ZXN0XFYxXEdQQk1ldGFkYXRh6gISU3Bhd25lcjo6UXVlc3Q6OlYxYgZwcm90bzM");

/**
 * Only output. Assumes that quests are implemented on the client-side, and
 * triggered by this event.
 *
 * @generated from message spawner.quest.v1.QuestEvent
 */
export type QuestEvent = Message<"spawner.quest.v1.QuestEvent"> & {
  /**
   * Relative resource path.
   * Format: `workspaces:{workspace_id}:quests:{quest_id}`
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Indicates the custom identifier of the quest.
   *
   * @generated from field: string custom_id = 2;
   */
  customId: string;

  /**
   * The agent id of the quest was issued by.
   *
   * @generated from field: string issuer_agent_id = 3;
   */
  issuerAgentId: string;

  /**
   * Flavor text to supplement the quest.
   *
   * @generated from field: string flavor_text = 4;
   */
  flavorText: string;
};

/**
 * Describes the message spawner.quest.v1.QuestEvent.
 * Use `create(QuestEventSchema)` to create a new message.
 */
export const QuestEventSchema: GenMessage<QuestEvent> = /*@__PURE__*/
  messageDesc(file_spawner_quest_v1_quest, 0);

