// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file spawner/observation/v1/observation.proto (package spawner.observation.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { QuestEvent } from "../../quest/v1/quest_pb";
import { file_spawner_quest_v1_quest } from "../../quest/v1/quest_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/observation/v1/observation.proto.
 */
export const file_spawner_observation_v1_observation: GenFile = /*@__PURE__*/
  fileDesc("CihzcGF3bmVyL29ic2VydmF0aW9uL3YxL29ic2VydmF0aW9uLnByb3RvEhZzcGF3bmVyLm9ic2VydmF0aW9uLnYxInMKEE9ic2VydmF0aW9uRXZlbnQSEAoIYWdlbnRfaWQYASABKAkSDAoEdGV4dBgCIAEoCRISCgppbXBvcnRhbmNlGAMgASgFEisKBXF1ZXN0GAQgASgLMhwuc3Bhd25lci5xdWVzdC52MS5RdWVzdEV2ZW50QqgBChpjb20uc3Bhd25lci5vYnNlcnZhdGlvbi52MUIQT2JzZXJ2YXRpb25Qcm90b1ABogIDU09YqgIWU3Bhd25lci5PYnNlcnZhdGlvbi5WMcoCFlNwYXduZXJcT2JzZXJ2YXRpb25cVjHiAiJTcGF3bmVyXE9ic2VydmF0aW9uXFYxXEdQQk1ldGFkYXRh6gIYU3Bhd25lcjo6T2JzZXJ2YXRpb246OlYxYgZwcm90bzM", [file_spawner_quest_v1_quest]);

/**
 * @generated from message spawner.observation.v1.ObservationEvent
 */
export type ObservationEvent = Message<"spawner.observation.v1.ObservationEvent"> & {
  /**
   * Required field.
   *
   * @generated from field: string agent_id = 1;
   */
  agentId: string;

  /**
   * Only input. Required field. The observation to add to the agent.
   *
   * @generated from field: string text = 2;
   */
  text: string;

  /**
   * Only input. Indicates the importance of the observation, represented as an
   * integer between 1 (low importance) and 9 (high importance). If a value is
   * not provided, value will be automatically detected.
   *
   * @generated from field: int32 importance = 3;
   */
  importance: number;

  /**
   * Only output. Filled when the observation triggers a quest issued by the
   * agent.
   *
   * @generated from field: spawner.quest.v1.QuestEvent quest = 4;
   */
  quest?: QuestEvent;
};

/**
 * Describes the message spawner.observation.v1.ObservationEvent.
 * Use `create(ObservationEventSchema)` to create a new message.
 */
export const ObservationEventSchema: GenMessage<ObservationEvent> = /*@__PURE__*/
  messageDesc(file_spawner_observation_v1_observation, 0);

