// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/actor/v1/actor.proto (package spawner.actor.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Encapsulates properties of a player. Used to populate the
 * user's profile for text generation, long-term memory management, etc.
 *
 * @generated from message spawner.actor.v1.PlayerActor
 */
export const PlayerActor = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.actor.v1.PlayerActor",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "age_group", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "gender", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Encapsulates the identifiers of a character.
 *
 * @generated from message spawner.actor.v1.CharacterActor
 */
export const CharacterActor = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.actor.v1.CharacterActor",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "display_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "custom_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Defines the actors within a channel.
 *
 * @generated from message spawner.actor.v1.Actor
 */
export const Actor = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.actor.v1.Actor",
  () => [
    { no: 1, name: "players", kind: "message", T: PlayerActor, repeated: true },
    { no: 2, name: "characters", kind: "message", T: CharacterActor, repeated: true },
  ],
);

