// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file spawner/actor/v1/actor.proto (package spawner.actor.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file spawner/actor/v1/actor.proto.
 */
export const file_spawner_actor_v1_actor: GenFile = /*@__PURE__*/
  fileDesc("ChxzcGF3bmVyL2FjdG9yL3YxL2FjdG9yLnByb3RvEhBzcGF3bmVyLmFjdG9yLnYxImcKC1BsYXllckFjdG9yEgoKAmlkGAEgASgJEhQKDGRpc3BsYXlfbmFtZRgCIAEoCRIRCglhZ2VfZ3JvdXAYAyABKAkSDgoGZ2VuZGVyGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJIkcKDkNoYXJhY3RlckFjdG9yEgwKBG5hbWUYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhEKCWN1c3RvbV9pZBgDIAEoCSJtCgVBY3RvchIuCgdwbGF5ZXJzGAEgAygLMh0uc3Bhd25lci5hY3Rvci52MS5QbGF5ZXJBY3RvchI0CgpjaGFyYWN0ZXJzGAIgAygLMiAuc3Bhd25lci5hY3Rvci52MS5DaGFyYWN0ZXJBY3RvckKEAQoUY29tLnNwYXduZXIuYWN0b3IudjFCCkFjdG9yUHJvdG9QAaICA1NBWKoCEFNwYXduZXIuQWN0b3IuVjHKAhBTcGF3bmVyXEFjdG9yXFYx4gIcU3Bhd25lclxBY3RvclxWMVxHUEJNZXRhZGF0YeoCElNwYXduZXI6OkFjdG9yOjpWMWIGcHJvdG8z");

/**
 * Encapsulates properties of a player. Used to populate the
 * user's profile for text generation, long-term memory management, etc.
 *
 * @generated from message spawner.actor.v1.PlayerActor
 */
export type PlayerActor = Message<"spawner.actor.v1.PlayerActor"> & {
  /**
   * Required field. Value should be unique for each player.
   * Spawner API does not verify consistency or uniqueness of the value.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Name of the player.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Age group of player.
   * Refer to latest documentation for expected values.
   *
   * @generated from field: string age_group = 3;
   */
  ageGroup: string;

  /**
   * Gender of player.
   * Refer to latest documentation for expected values.
   *
   * @generated from field: string gender = 4;
   */
  gender: string;

  /**
   * The text description of the player.
   *
   * @generated from field: string description = 5;
   */
  description: string;
};

/**
 * Describes the message spawner.actor.v1.PlayerActor.
 * Use `create(PlayerActorSchema)` to create a new message.
 */
export const PlayerActorSchema: GenMessage<PlayerActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 0);

/**
 * Encapsulates the identifiers of a character.
 *
 * @generated from message spawner.actor.v1.CharacterActor
 */
export type CharacterActor = Message<"spawner.actor.v1.CharacterActor"> & {
  /**
   * Only output. Relative resource path.
   * Format: `workspaces:{workspace_id}:characters:{character_id}`
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Name of the character.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Indicates the custom identifier of the character. Note that it
   * may differ from the character id used for storage.
   *
   * @generated from field: string custom_id = 3;
   */
  customId: string;
};

/**
 * Describes the message spawner.actor.v1.CharacterActor.
 * Use `create(CharacterActorSchema)` to create a new message.
 */
export const CharacterActorSchema: GenMessage<CharacterActor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 1);

/**
 * Defines the actors within a channel.
 *
 * @generated from message spawner.actor.v1.Actor
 */
export type Actor = Message<"spawner.actor.v1.Actor"> & {
  /**
   * @generated from field: repeated spawner.actor.v1.PlayerActor players = 1;
   */
  players: PlayerActor[];

  /**
   * @generated from field: repeated spawner.actor.v1.CharacterActor characters = 2;
   */
  characters: CharacterActor[];
};

/**
 * Describes the message spawner.actor.v1.Actor.
 * Use `create(ActorSchema)` to create a new message.
 */
export const ActorSchema: GenMessage<Actor> = /*@__PURE__*/
  messageDesc(file_spawner_actor_v1_actor, 2);

