// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/language_code/v1/language_code.proto (package spawner.language_code.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from enum spawner.language_code.v1.LanguageCode
 */
export declare enum LanguageCode {
  /**
   * @generated from enum value: LANGUAGE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LANGUAGE_CODE_EN = 1;
   */
  EN = 1,

  /**
   * @generated from enum value: LANGUAGE_CODE_JA = 2;
   */
  JA = 2,
}

