// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/language_code/v1/language_code.proto (package spawner.language_code.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum spawner.language_code.v1.LanguageCode
 */
export const LanguageCode = /*@__PURE__*/ proto3.makeEnum(
  "spawner.language_code.v1.LanguageCode",
  [
    {no: 0, name: "LANGUAGE_CODE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "LANGUAGE_CODE_EN", localName: "EN"},
    {no: 2, name: "LANGUAGE_CODE_JA", localName: "JA"},
  ],
);

