// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/text/v1/text.proto (package spawner.text.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message spawner.text.v1.CommandTriggered
 */
export const CommandTriggered = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.text.v1.CommandTriggered",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "custom_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * TextEvent represents text input and output.
 * Assumes output streamed per token using `delta` value.
 *
 * @generated from message spawner.text.v1.TextEvent
 */
export const TextEvent = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.text.v1.TextEvent",
  () => [
    { no: 1, name: "utterance_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "text", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "delta", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "final", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 5, name: "command", kind: "message", T: CommandTriggered },
  ],
);

