// @generated by protoc-gen-es v1.10.0
// @generated from file spawner/emotion/v1/emotion.proto (package spawner.emotion.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum spawner.emotion.v1.EmotionResult
 */
export const EmotionResult = /*@__PURE__*/ proto3.makeEnum(
  "spawner.emotion.v1.EmotionResult",
  [
    {no: 0, name: "EMOTION_RESULT_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "EMOTION_RESULT_NEUTRAL", localName: "NEUTRAL"},
    {no: 2, name: "EMOTION_RESULT_JOY", localName: "JOY"},
    {no: 3, name: "EMOTION_RESULT_SADNESS", localName: "SADNESS"},
    {no: 4, name: "EMOTION_RESULT_ANGER", localName: "ANGER"},
    {no: 5, name: "EMOTION_RESULT_FEAR", localName: "FEAR"},
    {no: 6, name: "EMOTION_RESULT_DISGUST", localName: "DISGUST"},
    {no: 7, name: "EMOTION_RESULT_SURPRISE", localName: "SURPRISE"},
  ],
);

/**
 * @generated from message spawner.emotion.v1.EmotionScore
 */
export const EmotionScore = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.emotion.v1.EmotionScore",
  () => [
    { no: 1, name: "joy", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 2, name: "sadness", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 3, name: "anger", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 4, name: "fear", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 5, name: "disgust", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
    { no: 6, name: "surprise", kind: "scalar", T: 2 /* ScalarType.FLOAT */ },
  ],
);

/**
 * Output only. Indicates the emotion detection results.
 *
 * @generated from message spawner.emotion.v1.EmotionEvent
 */
export const EmotionEvent = /*@__PURE__*/ proto3.makeMessageType(
  "spawner.emotion.v1.EmotionEvent",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "utterance_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "result", kind: "enum", T: proto3.getEnumType(EmotionResult) },
    { no: 4, name: "score", kind: "message", T: EmotionScore },
  ],
);

